version: "3.9"
services:
  cafe-api:
    container_name: cafe-api
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "8080:8080"
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - cafe-api